#!/bin/sh
#
# Copyright (c) 2012-2013, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

export PATH='/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin'

CONF_FILE="/etc/wlan_config"
SDIO_POLLING_PATH="/sys/devices/msm_sdcc.3/polling"

HOSTAPD_CONF="/etc/wlan2/hostapd.conf"
WPA_SUPPLICANT_CONF="/etc/wlan2/wpa_supplicant.conf"
WPA_SUPPLICANT_WEP_CONF="/etc/wlan2/wpa_supplicant_wep.conf"

#set -e

connect(){
    echo "Configuration file: $@"
    wpa_supplicant -B -Dwext -iwlan0 -c$1 1>/dev/null 2>/dev/null
    udhcpc -n -i wlan0 -s /etc/udhcpc.d/50default 1>/dev/null 2>/dev/null
    if [ $? -ne 0 ];then
        echo "Error wifi auth fail"
        killall wpa_supplicant
        return 1
    else
        iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE --random
    fi
}

if [ -r $CONF_FILE ]; then

    grep -iq "device=AR6003" $CONF_FILE
    if [ $? -ne 0 ]; then
        echo "AR6003 chip NOT detected!"
        exit 1
    fi

    case "$1" in
    start)
        $0 stop
        
        if [ -w $SDIO_POLLING_PATH ]; then
            echo 1 > $SDIO_POLLING_PATH
        else
            echo "Cannot write to $SDIO_POLLING_PATH"
            exit 1
        fi

        modprobe ar6000 targetconf="router" devmode="sta,ap" ifname="wlan"
        if [ $? -ne 0 ];then
            echo "Error to modprobe ar6000"
            exit 1
        fi
        sleep 3

        ifconfig wlan0 up
        ifconfig wlan1 up

        echo 0 > $SDIO_POLLING_PATH

        connect $WPA_SUPPLICANT_WEP_CONF
        if [ $? -ne 0 ];then
            connect $WPA_SUPPLICANT_CONF
        fi

        ping -c 1 -W 3 1.1.1.1 1>/dev/null 2>/dev/null
        if [ $? -ne 0 ];then
            echo "No internet. Setting rmnet0 default..."
            udhcpc -n -i rmnet0 -s /etc/udhcpc.d/50default 1>/dev/null 2>/dev/null
            if [ $? -ne 0 ];then
                echo "Error on set rmnet0 as default"
            fi
        fi

        #echo "Starting hostap..."
        #hostapd -B $HOSTAPD_CONF
        ;;

    stop)
        echo "Stopping WLAN..."
        killall -15 cxmapp hostapd dhcprelay wpa_supplicant udhcpc QCMAP_ConnectionManager 2>/dev/null
        iptables -t nat -F POSTROUTING
        echo 0 > $SDIO_POLLING_PATH
        
        ifconfig wlan0 down 1>/dev/null 2>/dev/null
        ifconfig wlan1 down 1>/dev/null 2>/dev/null

        rmmod ar6000
        sleep 3
        ;;

    restart)
        $0 stop
        shift
        $0 start $@

        if [ $? -ne 0 ]; then
            return 1
        fi
        ;;

    *)
        echo "Usage $0 {start | stop | restart}" >&2
        exit 1
        ;;
    esac
fi

exit 0
